{% set name = "napari-process-points-and-surfaces" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-process-points-and-surfaces-{{ version }}.tar.gz
  sha256: 3ed6a1b601c716f09f43bbc924f645211aa188d596c07323a9de2751a59fe1f2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8,<3.11
  run:
    - imageio !=2.22.1
    - napari
    - napari-plugin-engine >=0.1.4
    - napari-skimage-regionprops >=0.5.5
    - napari-time-slicer >=0.4.5
    - napari-tools-menu >=0.1.14
    - napari-workflows >=0.2.3
    - numpy
    - pandas
    - python >=3.8,<3.11
    - stackview >=0.5.2
    - vedo >=2022.4.1

test:
  imports:
    - napari_process_points_and_surfaces
  commands:
    - pip list
    # - pip check # Fails on windows due to vtk not being found by the pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/napari-process-points-and-surfaces
  summary: Process and analyze surfaces using open3d and vedo in napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - haesleinhuepf
    - jaimergp
